/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetSentRouteImport } from './routes/reset-sent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as ProfileTermsRouteImport } from './routes/profile.terms'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileChangePasswordRouteImport } from './routes/profile.change-password'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'
import { Route as AppointmentsIdRescheduleRouteImport } from './routes/appointments.$id.reschedule'
import { Route as AppointmentsIdCancelRouteImport } from './routes/appointments.$id.cancel'

const ResetSentRoute = ResetSentRouteImport.update({
  id: '/reset-sent',
  path: '/reset-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTermsRoute = ProfileTermsRouteImport.update({
  id: '/profile/terms',
  path: '/profile/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/profile/help',
  path: '/profile/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChangePasswordRoute = ProfileChangePasswordRouteImport.update({
  id: '/profile/change-password',
  path: '/profile/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRescheduleRoute =
  AppointmentsIdRescheduleRouteImport.update({
    id: '/reschedule',
    path: '/reschedule',
    getParentRoute: () => AppointmentsIdRoute,
  } as any)
const AppointmentsIdCancelRoute = AppointmentsIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => AppointmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-sent': typeof ResetSentRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/appointments/$id/reschedule': typeof AppointmentsIdRescheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-sent': typeof ResetSentRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/services': typeof ServicesIndexRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/appointments/$id/reschedule': typeof AppointmentsIdRescheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-sent': typeof ResetSentRoute
  '/appointments/$id': typeof AppointmentsIdRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/appointments/$id/cancel': typeof AppointmentsIdCancelRoute
  '/appointments/$id/reschedule': typeof AppointmentsIdRescheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/reset-sent'
    | '/appointments/$id'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/terms'
    | '/services/$serviceId'
    | '/appointments/'
    | '/profile/'
    | '/services/'
    | '/appointments/$id/cancel'
    | '/appointments/$id/reschedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/reset-sent'
    | '/appointments/$id'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/terms'
    | '/services/$serviceId'
    | '/appointments'
    | '/profile'
    | '/services'
    | '/appointments/$id/cancel'
    | '/appointments/$id/reschedule'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/reset-sent'
    | '/appointments/$id'
    | '/profile/addresses'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications'
    | '/profile/privacy'
    | '/profile/terms'
    | '/services/$serviceId'
    | '/appointments/'
    | '/profile/'
    | '/services/'
    | '/appointments/$id/cancel'
    | '/appointments/$id/reschedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetSentRoute: typeof ResetSentRoute
  AppointmentsIdRoute: typeof AppointmentsIdRouteWithChildren
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileChangePasswordRoute: typeof ProfileChangePasswordRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileTermsRoute: typeof ProfileTermsRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-sent': {
      id: '/reset-sent'
      path: '/reset-sent'
      fullPath: '/reset-sent'
      preLoaderRoute: typeof ResetSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/terms': {
      id: '/profile/terms'
      path: '/profile/terms'
      fullPath: '/profile/terms'
      preLoaderRoute: typeof ProfileTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/change-password': {
      id: '/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof ProfileChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id/reschedule': {
      id: '/appointments/$id/reschedule'
      path: '/reschedule'
      fullPath: '/appointments/$id/reschedule'
      preLoaderRoute: typeof AppointmentsIdRescheduleRouteImport
      parentRoute: typeof AppointmentsIdRoute
    }
    '/appointments/$id/cancel': {
      id: '/appointments/$id/cancel'
      path: '/cancel'
      fullPath: '/appointments/$id/cancel'
      preLoaderRoute: typeof AppointmentsIdCancelRouteImport
      parentRoute: typeof AppointmentsIdRoute
    }
  }
}

interface AppointmentsIdRouteChildren {
  AppointmentsIdCancelRoute: typeof AppointmentsIdCancelRoute
  AppointmentsIdRescheduleRoute: typeof AppointmentsIdRescheduleRoute
}

const AppointmentsIdRouteChildren: AppointmentsIdRouteChildren = {
  AppointmentsIdCancelRoute: AppointmentsIdCancelRoute,
  AppointmentsIdRescheduleRoute: AppointmentsIdRescheduleRoute,
}

const AppointmentsIdRouteWithChildren = AppointmentsIdRoute._addFileChildren(
  AppointmentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetSentRoute: ResetSentRoute,
  AppointmentsIdRoute: AppointmentsIdRouteWithChildren,
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileChangePasswordRoute: ProfileChangePasswordRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileTermsRoute: ProfileTermsRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
